name: community_dashboard
description: Community Safety & Infrastructure Dashboard
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  # State management
  provider: ^6.1.1
  # Maps and location
  flutter_map: ^6.0.1
  flutter_map_cancellable_tile_provider: ^2.0.0  # Updated version
  geolocator: ^9.0.2
  image_picker: ^0.8.7+3
  positioned_tap_detector_2: ^1.0.4
  image: ^4.0.15
  http: ^1.1.0
  latlong2: ^0.9.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
